[project]
name = "adventofcode2024"
version = "0.1.0"
description = "Advent of Code 2024 solutions in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.14.1",
    "tqdm>=4.67.1",
    "typer>=0.14.0",
]
